########################################################################################

# This Makefile generated by GoMakeGen 0.6.0 using next command:
# gomakegen .

########################################################################################

.PHONY = fmt all clean deps

########################################################################################

all: init-exporter-converter

init-exporter-converter:
	go build init-exporter-converter.go

deps:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v github.com/funbox/init-exporter
	go get -d -v pkg.re/essentialkaos/ek.v9
	go get -d -v pkg.re/essentialkaos/go-simpleyaml.v1

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

clean:
	rm -f init-exporter-converter

########################################################################################
