################################################################################

# This Makefile generated by GoMakeGen 0.8.0 using next command:
# gomakegen .

################################################################################

.DEFAULT_GOAL := help
.PHONY = fmt all clean deps help

################################################################################

all: init-exporter-converter ## Build all binaries

init-exporter-converter: ## Build init-exporter-converter binary
	go build init-exporter-converter.go

install: ## Install binaries
	cp init-exporter-converter /usr/bin/init-exporter-converter

uninstall: ## Uninstall binaries
	rm -f /usr/bin/init-exporter-converter

deps: ## Download dependencies
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v github.com/funbox/init-exporter
	go get -d -v pkg.re/essentialkaos/ek.v9
	go get -d -v pkg.re/essentialkaos/go-simpleyaml.v1

fmt: ## Format source code with gofmt
	find . -name "*.go" -exec gofmt -s -w {} \;

clean: ## Remove generated files
	rm -f init-exporter-converter

help: ## Show this info
	@echo -e '\nSupported targets:\n'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[33m%-12s\033[0m %s\n", $$1, $$2}'
	@echo -e ''

################################################################################
